---
abstract: 'A Base Class for Gentoo MetaEbuild Specifications.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FindBin: '0'
  Test::Fatal: '0'
  Test::File::ShareDir::Module: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Gentoo-MetaEbuild-Spec-Base
provides:
  Gentoo::MetaEbuild::Spec::Base:
    file: lib/Gentoo/MetaEbuild/Spec/Base.pm
    version: '1.000002'
recommends:
  Moose: '2.000'
  Path::Tiny: '0.058'
requires:
  Carp: '0'
  Data::Rx: '0'
  File::ShareDir: '0'
  JSON::MaybeXS: '0'
  Moose: '0'
  MooseX::ClassAttribute: '0'
  MooseX::Has::Sugar: '0'
  MooseX::Types::Moose: '0'
  MooseX::Types::Path::Tiny: '0'
  MooseX::Types::Perl: '0'
  Path::Tiny: '0'
  Scalar::Util: '0'
  namespace::autoclean: '0'
  perl: '5.006'
  strict: '0'
  version: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Gentoo-MetaEbuild-Spec-Base/issues
  homepage: https://github.com/kentnl/Gentoo-MetaEbuild-Spec-Base
  repository: https://github.com/kentnl/Gentoo-MetaEbuild-Spec-Base.git
version: '1.000002'
